name: "API Rest CI"

on:
  pull_request:
  push:
    branches:
      - "main"

defaults:
  run:
    shell: bash

jobs:
  integration:
    strategy:
      fail-fast: false
      matrix: 
        node_verision: [15.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Configure Nodejs"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Install Packages"
        run: npm ci
      - name: Run Tests
        run: npm test -- --coverage
      - name: "Build Application"
        run: |
          mkdir -p dist/
          zip -r dist.zip . -x node_modules/**\*; mv dist.zip dist/
          zip -r coverage.zip coverage/; mv coverage.zip dist/
      - name: "Store artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: distributable
          path: dist/
      - name: "Create Release"
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    